from PySide2 import QtCore, QtWidgets


class CgDoubleSpinBox(QtWidgets.QDoubleSpinBox):
    
    def __init__(self, parent=None):
        super(CgDoubleSpinBox, self).__init__(parent)
        self.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))

    def wheelEvent(self, event):
        if self.isEnabled():
            super(CgDoubleSpinBox, self).wheelEvent(event)
        else:
            event.ignore()

class CgCheckBox(QtWidgets.QCheckBox):
    checkBoxEmit = QtCore.Signal(str)
    
    def __init__(self, parent=None):
        super(CgCheckBox, self).__init__(parent)
        self.checkBoxName = "Undefined"

    def mousePressEvent(self, event):
        self.checkBoxEmit.emit(self.checkBoxName)
        super(CgCheckBox, self).mousePressEvent(event)

class CgPushButton(QtWidgets.QPushButton):
    buttonName = QtCore.Signal(int)

    def __init__(self, parent=None):
        super(CgPushButton, self).__init__(parent)
        self.emittedName = 0

    def mousePressEvent(self, event):
        self.buttonName.emit(self.emittedName)
        super(CgPushButton, self).mousePressEvent(event)


class Ui_CG(object):
    def setupUi(self, CG):
        CG.setObjectName("CG")
        CG.resize(432, 244)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CG.sizePolicy().hasHeightForWidth())
        CG.setSizePolicy(sizePolicy)
        lockObject(CG, 432, 244)
        self.gridLayoutWidget = QtWidgets.QWidget(CG)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 231, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.constraintTypeLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.constraintTypeLayout.setContentsMargins(8, -1, -1, -1)
        self.constraintTypeLayout.setHorizontalSpacing(0)
        self.constraintTypeLayout.setObjectName("constraintTypeLayout")
        self.CTL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(91)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.CTL.sizePolicy().hasHeightForWidth())
        self.CTL.setSizePolicy(sizePolicy)
        lockObject(self.CTL, 91, 20)
        self.CTL.setBaseSize(QtCore.QSize(91, 20))
        self.CTL.setObjectName("CTL")
        self.constraintTypeLayout.addWidget(self.CTL, 0, 0, 1, 1)
        self.constraintCB = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.constraintCB.sizePolicy().hasHeightForWidth())
        self.constraintCB.setSizePolicy(sizePolicy)
        lockObject(self.constraintCB, 131, 20)
        self.constraintCB.setBaseSize(QtCore.QSize(131, 21))
        self.constraintCB.setFrame(False)
        self.constraintCB.setModelColumn(0)
        self.constraintCB.setObjectName("constraintCB")
        self.constraintCB.addItem("")
        self.constraintCB.addItem("")
        self.constraintCB.addItem("")
        self.constraintCB.addItem("")
        self.constraintCB.addItem("")
        self.constraintCB.addItem("")
        self.constraintTypeLayout.addWidget(self.constraintCB, 0, 1, 1, 1)
        self.wutL = QtWidgets.QLabel(self.gridLayoutWidget)
        lockObject(self.wutL, 91, 20)
        self.wutL.setObjectName("wutL")
        self.constraintTypeLayout.addWidget(self.wutL, 1, 0, 1, 1)
        self.wutCB = QtWidgets.QComboBox(self.gridLayoutWidget)
        lockObject(self.wutCB, 131, 21)
        self.wutCB.setObjectName("wutCB")
        self.wutCB.addItem("")
        self.wutCB.addItem("")
        self.wutCB.addItem("")
        self.wutCB.addItem("")
        self.constraintTypeLayout.addWidget(self.wutCB, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(CG)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 61, 231, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.skipTLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.skipTLayout.setContentsMargins(8, -1, -1, -1)
        self.skipTLayout.setObjectName("skipTLayout")
        self.skipTchkbZ = CgCheckBox(self.gridLayoutWidget_2)
        self.skipTchkbZ.setObjectName("skipTchkbZ")
        self.skipTLayout.addWidget(self.skipTchkbZ, 0, 4, 1, 1)
        self.skipTchkbY = CgCheckBox(self.gridLayoutWidget_2)
        self.skipTchkbY.setObjectName("skipTchkbY")
        self.skipTLayout.addWidget(self.skipTchkbY, 0, 3, 1, 1)
        self.skipTchkbX = CgCheckBox(self.gridLayoutWidget_2)
        self.skipTchkbX.setObjectName("skipTchkbX")
        self.skipTLayout.addWidget(self.skipTchkbX, 0, 2, 1, 1)
        self.translateL = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translateL.sizePolicy().hasHeightForWidth())
        self.translateL.setSizePolicy(sizePolicy)
        self.translateL.setMinimumSize(QtCore.QSize(65, 20))
        self.translateL.setObjectName("translateL")
        self.skipTLayout.addWidget(self.translateL, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.skipTLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(CG)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 100, 231, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.skipRLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.skipRLayout.setContentsMargins(43, -1, -1, -1)
        self.skipRLayout.setObjectName("skipRLayout")
        self.skipRchkbY = CgCheckBox(self.gridLayoutWidget_3)
        self.skipRchkbY.setObjectName("skipRchkbY")
        self.skipRLayout.addWidget(self.skipRchkbY, 0, 2, 1, 1)
        self.rotateL = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateL.sizePolicy().hasHeightForWidth())
        self.rotateL.setSizePolicy(sizePolicy)
        self.rotateL.setMinimumSize(QtCore.QSize(65, 20))
        self.rotateL.setObjectName("rotateL")
        self.skipRLayout.addWidget(self.rotateL, 0, 0, 1, 1)
        self.skipRchkbX = CgCheckBox(self.gridLayoutWidget_3)
        self.skipRchkbX.setObjectName("skipRchkbX")
        self.skipRLayout.addWidget(self.skipRchkbX, 0, 1, 1, 1)
        self.skipRchkbZ = CgCheckBox(self.gridLayoutWidget_3)
        self.skipRchkbZ.setObjectName("skipRchkbZ")
        self.skipRLayout.addWidget(self.skipRchkbZ, 0, 3, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(CG)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 130, 231, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.vectorNameLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.vectorNameLayout.setContentsMargins(12, -1, -1, -1)
        self.vectorNameLayout.setObjectName("vectorNameLayout")
        self.vectorNameL = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.vectorNameL.setObjectName("vectorNameL")
        self.vectorNameLayout.addWidget(self.vectorNameL, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        lockObject(self.lineEdit, 133, 20)
        self.lineEdit.setBaseSize(QtCore.QSize(5, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.vectorNameLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.buQueryVec = CgPushButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buQueryVec.sizePolicy().hasHeightForWidth())
        self.buQueryVec.setSizePolicy(sizePolicy)
        lockObject(self.buQueryVec, 35, 20)
        self.buQueryVec.setObjectName("buQueryVec")
        self.vectorNameLayout.addWidget(self.buQueryVec, 0, 2, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(CG)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(240, 30, 191, 141))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.vectorLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.vectorLayout.setContentsMargins(7, -1, -1, -1)
        self.vectorLayout.setHorizontalSpacing(3)
        self.vectorLayout.setVerticalSpacing(0)
        self.vectorLayout.setObjectName("vectorLayout")
        self.vecWUZ = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecWUZ, 40, 20)
        self.vecWUZ.setFrame(True)
        self.vecWUZ.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecWUZ.setDecimals(3)
        self.vecWUZ.setMaximum(1.0)
        self.vecWUZ.setSingleStep(0.01)
        self.vecWUZ.setObjectName("vecWUZ")
        self.vectorLayout.addWidget(self.vecWUZ, 5, 3, 1, 1)
        self.buAimZ = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buAimZ.sizePolicy().hasHeightForWidth())
        self.buAimZ.setSizePolicy(sizePolicy)
        lockObject(self.buAimZ, 42, 18)
        self.buAimZ.setObjectName("buAimZ")
        self.vectorLayout.addWidget(self.buAimZ, 0, 3, 1, 1)
        self.buAimY = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buAimY.sizePolicy().hasHeightForWidth())
        self.buAimY.setSizePolicy(sizePolicy)
        lockObject(self.buAimY, 42, 18)
        self.buAimY.setObjectName("buAimY")
        self.vectorLayout.addWidget(self.buAimY, 0, 2, 1, 1)
        self.buUpX = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buUpX.sizePolicy().hasHeightForWidth())
        self.buUpX.setSizePolicy(sizePolicy)
        lockObject(self.buUpX, 42, 18)
        self.buUpX.setObjectName("buUpX")
        self.vectorLayout.addWidget(self.buUpX, 2, 1, 1, 1)
        self.vecWUY = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecWUY, 40, 20)
        self.vecWUY.setFrame(True)
        self.vecWUY.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecWUY.setDecimals(3)
        self.vecWUY.setMaximum(1.0)
        self.vecWUY.setSingleStep(0.01)
        self.vecWUY.setObjectName("vecWUY")
        self.vectorLayout.addWidget(self.vecWUY, 5, 2, 1, 1)
        self.vecUpY = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecUpY, 40, 20)
        self.vecUpY.setFrame(True)
        self.vecUpY.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecUpY.setDecimals(3)
        self.vecUpY.setMaximum(1.0)
        self.vecUpY.setSingleStep(0.01)
        self.vecUpY.setObjectName("vecUpY")
        self.vectorLayout.addWidget(self.vecUpY, 3, 2, 1, 1)
        self.vecUpZ = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecUpZ, 40, 20)
        self.vecUpZ.setMaximumSize(QtCore.QSize(40, 20))
        self.vecUpZ.setFrame(True)
        self.vecUpZ.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecUpZ.setDecimals(3)
        self.vecUpZ.setMaximum(1.0)
        self.vecUpZ.setSingleStep(0.01)
        self.vecUpZ.setObjectName("vecUpZ")
        self.vectorLayout.addWidget(self.vecUpZ, 3, 3, 1, 1)
        self.buAimX = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buAimX.sizePolicy().hasHeightForWidth())
        self.buAimX.setSizePolicy(sizePolicy)
        lockObject(self.buAimX, 42, 18)
        self.buAimX.setObjectName("buAimX")
        self.vectorLayout.addWidget(self.buAimX, 0, 1, 1, 1)
        self.vecUpX = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecUpX, 40, 20)
        self.vecUpX.setMaximumSize(QtCore.QSize(40, 20))
        self.vecUpX.setFrame(True)
        self.vecUpX.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecUpX.setDecimals(3)
        self.vecUpX.setMaximum(1.0)
        self.vecUpX.setSingleStep(0.01)
        self.vecUpX.setObjectName("vecUpX")
        self.vectorLayout.addWidget(self.vecUpX, 3, 1, 1, 1)
        self.vecWUX = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecWUX, 40, 20)
        self.vecWUX.setFrame(True)
        self.vecWUX.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecWUX.setDecimals(3)
        self.vecWUX.setMaximum(1.0)
        self.vecWUX.setSingleStep(0.01)
        self.vecWUX.setObjectName("vecWUX")
        self.vectorLayout.addWidget(self.vecWUX, 5, 1, 1, 1)
        self.vecAimX = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecAimX, 40, 20)
        self.vecAimX.setFrame(True)
        self.vecAimX.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecAimX.setDecimals(3)
        self.vecAimX.setMaximum(1.0)
        self.vecAimX.setSingleStep(0.01)
        self.vecAimX.setObjectName("vecAimX")
        self.vectorLayout.addWidget(self.vecAimX, 1, 1, 1, 1)
        self.aimL = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.aimL.setObjectName("aimL")
        self.vectorLayout.addWidget(self.aimL, 1, 0, 1, 1)
        self.buUpZ = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buUpZ.sizePolicy().hasHeightForWidth())
        self.buUpZ.setSizePolicy(sizePolicy)
        lockObject(self.buUpZ, 42, 18)
        self.buUpZ.setObjectName("buUpZ")
        self.vectorLayout.addWidget(self.buUpZ, 2, 3, 1, 1)
        self.vecAimZ = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecAimZ, 40, 20)
        self.vecAimZ.setFrame(True)
        self.vecAimZ.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecAimZ.setDecimals(3)
        self.vecAimZ.setMaximum(1.0)
        self.vecAimZ.setSingleStep(0.01)
        self.vecAimZ.setObjectName("vecAimZ")
        self.vectorLayout.addWidget(self.vecAimZ, 1, 3, 1, 1)
        self.WUL = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.WUL.setObjectName("WUL")
        self.vectorLayout.addWidget(self.WUL, 5, 0, 1, 1)
        self.UpL = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.UpL.setObjectName("UpL")
        self.vectorLayout.addWidget(self.UpL, 3, 0, 1, 1)
        self.vecAimY = CgDoubleSpinBox(self.gridLayoutWidget_5)
        lockObject(self.vecAimY, 40, 20)
        self.vecAimY.setFrame(True)
        self.vecAimY.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vecAimY.setDecimals(3)
        self.vecAimY.setMaximum(1.0)
        self.vecAimY.setSingleStep(0.01)
        self.vecAimY.setObjectName("vecAimY")
        self.vectorLayout.addWidget(self.vecAimY, 1, 2, 1, 1)
        self.buUpY = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buUpY.sizePolicy().hasHeightForWidth())
        self.buUpY.setSizePolicy(sizePolicy)
        lockObject(self.buUpY, 42, 18)
        self.buUpY.setObjectName("buUpY")
        self.vectorLayout.addWidget(self.buUpY, 2, 2, 1, 1)
        self.buWUX = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buWUX.sizePolicy().hasHeightForWidth())
        self.buWUX.setSizePolicy(sizePolicy)
        lockObject(self.buWUX, 42, 18)
        self.buWUX.setObjectName("buWUX")
        self.vectorLayout.addWidget(self.buWUX, 4, 1, 1, 1)
        self.buWUY = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buWUY.sizePolicy().hasHeightForWidth())
        self.buWUY.setSizePolicy(sizePolicy)
        lockObject(self.buWUY, 42, 18)
        self.buWUY.setObjectName("buWUY")
        self.vectorLayout.addWidget(self.buWUY, 4, 2, 1, 1)
        self.buWUZ = CgPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buWUZ.sizePolicy().hasHeightForWidth())
        self.buWUZ.setSizePolicy(sizePolicy)
        lockObject(self.buWUZ, 42, 18)
        self.buWUZ.setObjectName("buWUZ")
        self.vectorLayout.addWidget(self.buWUZ, 4, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(CG)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 0, 16, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.sepLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.sepLayout.setContentsMargins(5, -1, -1, 4)
        self.sepLayout.setObjectName("sepLayout")
        self.vrSep1 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.vrSep1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vrSep1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vrSep1.setObjectName("vrSep1")
        self.sepLayout.addWidget(self.vrSep1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(CG)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(240, 0, 191, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.vectorLabelLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.vectorLabelLayout.setContentsMargins(3, -1, -1, -1)
        self.vectorLabelLayout.setObjectName("vectorLabelLayout")
        self.vectorL = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.vectorL.setObjectName("vectorL")
        self.vectorLabelLayout.addWidget(self.vectorL)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(CG)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 170, 234, 22))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.paramLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.paramLayout.setContentsMargins(0, 0, 0, 0)
        self.paramLayout.setObjectName("paramLayout")
        self.MOchkb = CgCheckBox(self.gridLayoutWidget_6)
        lockObject(self.MOchkb, 95, 20)
        self.MOchkb.setChecked(True)
        self.MOchkb.setTristate(False)
        self.MOchkb.setObjectName("MOchkb")
        self.paramLayout.addWidget(self.MOchkb, 0, 0, 1, 1)
        self.MCchkb = CgCheckBox(self.gridLayoutWidget_6)
        lockObject(self.MCchkb, 131, 20)
        self.MCchkb.setObjectName("MCchkb")
        self.paramLayout.addWidget(self.MCchkb, 0, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(CG)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 160, 431, 16))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.sepLayout2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.sepLayout2.setContentsMargins(0, 0, 0, 0)
        self.sepLayout2.setObjectName("sepLayout2")
        self.hrSep3 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.hrSep3.setFrameShape(QtWidgets.QFrame.HLine)
        self.hrSep3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hrSep3.setObjectName("hrSep3")
        self.sepLayout2.addWidget(self.hrSep3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(CG)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(100, 190, 133, 22))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.modeLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.modeLayout.setContentsMargins(0, 0, 0, 0)
        self.modeLayout.setObjectName("modeLayout")
        self.aToA = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        lockObject(self.aToA, 65, 20)
        self.aToA.setObjectName("aToA")
        self.modeLayout.addWidget(self.aToA)
        self.AToO = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        lockObject(self.AToO, 65, 20)
        self.AToO.setObjectName("AToO")
        self.modeLayout.addWidget(self.AToO)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(CG)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 210, 231, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.weightLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.weightLayout.setContentsMargins(25, -1, 64, -1)
        self.weightLayout.setObjectName("weightLayout")
        self.weightL = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.weightL.setObjectName("weightL")
        self.weightLayout.addWidget(self.weightL)
        self.weightSB = CgDoubleSpinBox(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightSB.sizePolicy().hasHeightForWidth())
        self.weightSB.setSizePolicy(sizePolicy)
        lockObject(self.weightSB, 68, 20)
        self.weightSB.setBaseSize(QtCore.QSize(68, 0))
        self.weightSB.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.weightSB.setDecimals(3)
        self.weightSB.setMaximum(1.0)
        self.weightSB.setSingleStep(0.01)
        self.weightSB.setProperty("value", 1.0)
        self.weightSB.setObjectName("weightSB")
        self.weightLayout.addWidget(self.weightSB)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(CG)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(230, 170, 201, 71))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.applyLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.applyLayout.setContentsMargins(6, -1, 6, -1)
        self.applyLayout.setObjectName("applyLayout")
        self.buApply = CgPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buApply.sizePolicy().hasHeightForWidth())
        self.buApply.setSizePolicy(sizePolicy)
        self.buApply.setMinimumSize(QtCore.QSize(100, 30))
        self.buApply.setObjectName("buApply")
        self.applyLayout.addWidget(self.buApply)
        self.buClose = CgPushButton(self.horizontalLayoutWidget_5)
        self.buClose.setMinimumSize(QtCore.QSize(0, 30))
        self.buClose.setObjectName("buClose")
        self.applyLayout.addWidget(self.buClose)

        self.retranslateUi(CG)
        self.constraintCB.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(CG)

    def retranslateUi(self, CG):
        CG.setWindowTitle("Constraints")
        self.CTL.setText("Constraint type:")
        self.constraintCB.setItemText(0, "pointConstraint")
        self.constraintCB.setItemText(1, "orientConstraint")
        self.constraintCB.setItemText(2, "scaleConstraint")
        self.constraintCB.setItemText(3, "aimConstraint")
        self.constraintCB.setItemText(4, "parentConstraint")
        self.constraintCB.setItemText(5, "poleVectorConstraint")
        self.wutL.setText("World up type:")
        self.wutCB.setItemText(0, "Object")
        self.wutCB.setItemText(1, "Object Rotation")
        self.wutCB.setItemText(2, "Vector")
        self.wutCB.setItemText(3, "Scene")
        self.skipTchkbZ.setText("Z")
        self.skipTchkbY.setText("Y")
        self.skipTchkbX.setText("X")
        self.translateL.setText("Translate:")
        self.label.setText("Skip:")
        self.skipRchkbY.setText("Y")
        self.rotateL.setText("Rotate:")
        self.skipRchkbX.setText("X")
        self.skipRchkbZ.setText("Z")
        self.vectorNameL.setText("Vector: ")
        self.buQueryVec.setText("<<")
        self.buAimZ.setText("Z")
        self.buAimY.setText("Y")
        self.buUpX.setText("X")
        self.buAimX.setText("X")
        self.aimL.setText("Aim:")
        self.buUpZ.setText("Z")
        self.WUL.setText("World up:")
        self.UpL.setText("Up:")
        self.buUpY.setText("Y")
        self.buWUX.setText("X")
        self.buWUY.setText("Y")
        self.buWUZ.setText("Z")
        self.vectorL.setText("Vectors:")
        self.MOchkb.setText("Maintain Offset")
        self.MCchkb.setText("Multiple constraints")
        self.aToA.setText("All to all")
        self.AToO.setText("All to one")
        self.weightL.setText("Weight:")
        self.buApply.setText("Apply")
        self.buClose.setText("Close")

def lockObject(obj, w, h, QSize=True):
    if QSize:
        obj.setMinimumSize(QtCore.QSize(w,h))
        obj.setMaximumSize(QtCore.QSize(w,h))
    else:
        obj.setMinimumSize(w,h)
        obj.setMaximumSize(w,h)     
